TOP = ../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#
ARCHIVE += rfInterlockSeq.tpl-arch
ARCHIVE += rtmInterlock.tpl-arch
ARCHIVE += rtmWaveform.tpl-arch

ARCHIVE += interlockRtm.archive

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
#
# End of File


